sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: 4tkahDVj1RYU3a2+sewXFWpLgOyEkXh/q+pkNC/kgPZRVhTuQ/gdg9rkb3W4uML1FH029GIXGMPBVGTJ9z9QpaIoNC9MArXXUQqo/fSF20Mk8Zdd4ZqiKcGcZjxF1HnG4wvfMP4seP6wJrnXp2Xa9SJku1M9cX2NAYYfw9x6g/Xt6p0uZ+L2pCsrUaNmHZMOgvnnf+raNf/n/T++bCj0Kl5fpCtE1Zyhz8C5WXbiHkcKu94aH1jKBeV3m02YT/nN7T9Ql+OIm8klTdUpjmJHTBSjaVQGcmQJslkfaEFXbt6GERKL74wXRU8lUCL8wQUP7B4qs5NVALbLDX68r/WnhjuYoiJPvElITxNFhd5sbkHBDY6o7DsMSMvObQNrDoBgkw3vrX6Uiwfn9O4TVIAJofJIAgIbYsbaqcx1O/q05q8MVf8q6qtrt7Zxwcnyjs3dKf+t/YlNxxZcqBRr8I3LGhgKzxRkSu0qgUhLVcVbYR3QxVSG4B5aNQ3mG/wUof2x4O4nLxdbvameFJISs0Ya/fzLbAPQKOcic1s9ok/W2jXEIC4AV6Qwc2z1g2BB61Uv8rMIEHX6fkyDmUVBjtm5WgaXNpSVNuA2ljysg4OmY4cpfGUF3WcVCfvSG35t6+dr7nXldGxGlaGzeZsSS1TcYWFTFAAjIStltMxBTDaGtiY=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/Ballads-of-a-Bohemian_995
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy